# Generated by Django 3.0.7 on 2020-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('rcNo', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
