# Generated by Django 3.0.7 on 2020-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='phNo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
