# Generated by Django 3.0.7 on 2020-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0002_salesdata_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='phNo',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
