# Generated by Django 3.0.7 on 2020-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0003_auto_20200605_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='phNo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
