# Generated by Django 3.0.7 on 2020-06-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0004_auto_20200605_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcNo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
