# Generated by Django 3.0.7 on 2020-06-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0005_csr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='model',
            new_name='version',
        ),
    ]
