# Generated by Django 3.0.7 on 2020-06-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0006_auto_20200605_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phNo', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('rcNo', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, choices=[('ASSIGNED', 'ASSIGNED'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='ASSIGNED', max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='version',
            new_name='model',
        ),
    ]
