# Generated by Django 3.0.7 on 2020-06-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0007_auto_20200611_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertrack',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
