# Generated by Django 3.0.7 on 2020-06-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0008_auto_20200611_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertrack',
            name='customer_token',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
