# Generated by Django 3.0.7 on 2020-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0009_customertrack_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertrack',
            name='customer_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
