# Generated by Django 3.0.7 on 2020-06-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoMeter', models.DecimalField(decimal_places=5, max_digits=5)),
                ('fuelLevel', models.CharField(blank=True, default=('1', '1'), max_length=7, null=True)),
                ('cdPlayer', models.BooleanField(default=False)),
                ('cigrateCharger', models.BooleanField(default=False)),
                ('toolKit', models.BooleanField(default=False)),
                ('serviceBook', models.BooleanField(default=False)),
                ('clock', models.BooleanField(default=False)),
                ('perfume', models.BooleanField(default=False)),
                ('jack', models.BooleanField(default=False)),
                ('spareWheel', models.BooleanField(default=False)),
                ('mats', models.BooleanField(default=False)),
                ('dickyMat', models.BooleanField(default=False)),
                ('bodyCover', models.BooleanField(default=False)),
                ('antenna', models.BooleanField(default=False)),
                ('remote', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('customerRemarks', models.TextField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
