# Generated by Django 3.0.7 on 2020-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='fuelLevel',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('3', '3'), ('4', '4')], default=('1', '1'), max_length=7, null=True),
        ),
    ]
