# Generated by Django 3.0.7 on 2020-06-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0006_auto_20200605_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='odoMeter',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
