# Generated by Django 3.0.7 on 2020-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0009_auto_20200605_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='odoMeter1',
        ),
        migrations.AddField(
            model_name='pickup',
            name='odoMetervalue',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
