# Generated by Django 3.0.7 on 2020-06-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0010_auto_20200605_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('Drop', 'Drop')], max_length=7, null=True),
        ),
    ]
