# Generated by Django 3.0.7 on 2020-06-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0006_auto_20200605_2329'),
        ('Pickup', '0011_pickup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='rcNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CustomerData.CSR'),
        ),
    ]
