# Generated by Django 3.0.7 on 2020-06-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0012_pickup_rcno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='rcNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
