# Generated by Django 3.0.7 on 2020-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0013_auto_20200606_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
