# Generated by Django 3.0.7 on 2020-06-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0014_auto_20200606_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='status',
        ),
    ]
